"""
SmartCrop AI: Agronomic, Economic, and Hydrological Knowledge Base
Contains field benchmarks for all 22 crops in the crop recommendation dataset.
"""

CROP_DATABASE = {
    "rice": {
        "sowing_window": "June 15 – July 15 (Kharif)",
        "season": "Kharif",
        "seed_cost_per_acre": 2500,
        "fertilizer_cost_per_acre": 4500,
        "labor_cost_per_acre": 7000,
        "machinery_cost_per_acre": 3000,
        "irrigation_cost_per_acre": 2500,
        "pesticide_cost_per_acre": 1500,
        "water_requirement_mm": 1250,
        "expected_yield_quintal_per_acre": 22,
        "market_price_per_quintal": 2200,
        "market_demand": "High",
        "market_risk": "Low",
        "water_sensitivity": "High"
    },
    "maize": {
        "sowing_window": "June 15 – July 10 (Kharif) / Oct 15 – Nov 15 (Rabi)",
        "season": "Kharif / Rabi",
        "seed_cost_per_acre": 2200,
        "fertilizer_cost_per_acre": 3500,
        "labor_cost_per_acre": 4000,
        "machinery_cost_per_acre": 2500,
        "irrigation_cost_per_acre": 1500,
        "pesticide_cost_per_acre": 1300,
        "water_requirement_mm": 550,
        "expected_yield_quintal_per_acre": 25,
        "market_price_per_quintal": 2000,
        "market_demand": "High",
        "market_risk": "Medium",
        "water_sensitivity": "Medium"
    },
    "chickpea": {
        "sowing_window": "October 15 – November 20 (Rabi)",
        "season": "Rabi",
        "seed_cost_per_acre": 3000,
        "fertilizer_cost_per_acre": 2500,
        "labor_cost_per_acre": 3500,
        "machinery_cost_per_acre": 2000,
        "irrigation_cost_per_acre": 1000,
        "pesticide_cost_per_acre": 1500,
        "water_requirement_mm": 350,
        "expected_yield_quintal_per_acre": 8,
        "market_price_per_quintal": 5400,
        "market_demand": "High",
        "market_risk": "Low",
        "water_sensitivity": "Low"
    },
    "kidneybeans": {
        "sowing_window": "May 15 – June 20 (Kharif)",
        "season": "Kharif",
        "seed_cost_per_acre": 4000,
        "fertilizer_cost_per_acre": 2800,
        "labor_cost_per_acre": 4000,
        "machinery_cost_per_acre": 2000,
        "irrigation_cost_per_acre": 1200,
        "pesticide_cost_per_acre": 1600,
        "water_requirement_mm": 450,
        "expected_yield_quintal_per_acre": 6,
        "market_price_per_quintal": 7500,
        "market_demand": "Medium",
        "market_risk": "Medium",
        "water_sensitivity": "Medium"
    },
    "pigeonpeas": {
        "sowing_window": "June 15 – July 15 (Kharif)",
        "season": "Kharif",
        "seed_cost_per_acre": 2000,
        "fertilizer_cost_per_acre": 3000,
        "labor_cost_per_acre": 4500,
        "machinery_cost_per_acre": 2200,
        "irrigation_cost_per_acre": 1000,
        "pesticide_cost_per_acre": 1800,
        "water_requirement_mm": 600,
        "expected_yield_quintal_per_acre": 7,
        "market_price_per_quintal": 7000,
        "market_demand": "High",
        "market_risk": "Low",
        "water_sensitivity": "Low"
    },
    "mothbeans": {
        "sowing_window": "July 1 – July 25 (Kharif)",
        "season": "Kharif",
        "seed_cost_per_acre": 1500,
        "fertilizer_cost_per_acre": 1800,
        "labor_cost_per_acre": 3000,
        "machinery_cost_per_acre": 1800,
        "irrigation_cost_per_acre": 600,
        "pesticide_cost_per_acre": 800,
        "water_requirement_mm": 300,
        "expected_yield_quintal_per_acre": 4,
        "market_price_per_quintal": 6500,
        "market_demand": "Medium",
        "market_risk": "Medium",
        "water_sensitivity": "Low"
    },
    "mungbean": {
        "sowing_window": "June 20 – July 15 (Kharif)",
        "season": "Kharif",
        "seed_cost_per_acre": 1800,
        "fertilizer_cost_per_acre": 2200,
        "labor_cost_per_acre": 3500,
        "machinery_cost_per_acre": 1800,
        "irrigation_cost_per_acre": 800,
        "pesticide_cost_per_acre": 1200,
        "water_requirement_mm": 350,
        "expected_yield_quintal_per_acre": 5,
        "market_price_per_quintal": 7200,
        "market_demand": "High",
        "market_risk": "Medium",
        "water_sensitivity": "Low"
    },
    "blackgram": {
        "sowing_window": "June 15 – July 10 (Kharif)",
        "season": "Kharif",
        "seed_cost_per_acre": 1800,
        "fertilizer_cost_per_acre": 2200,
        "labor_cost_per_acre": 3500,
        "machinery_cost_per_acre": 1800,
        "irrigation_cost_per_acre": 800,
        "pesticide_cost_per_acre": 1200,
        "water_requirement_mm": 400,
        "expected_yield_quintal_per_acre": 5,
        "market_price_per_quintal": 6800,
        "market_demand": "High",
        "market_risk": "Low",
        "water_sensitivity": "Low"
    },
    "lentil": {
        "sowing_window": "October 20 – November 20 (Rabi)",
        "season": "Rabi",
        "seed_cost_per_acre": 2500,
        "fertilizer_cost_per_acre": 2200,
        "labor_cost_per_acre": 3500,
        "machinery_cost_per_acre": 1800,
        "irrigation_cost_per_acre": 800,
        "pesticide_cost_per_acre": 1100,
        "water_requirement_mm": 350,
        "expected_yield_quintal_per_acre": 6,
        "market_price_per_quintal": 6200,
        "market_demand": "High",
        "market_risk": "Low",
        "water_sensitivity": "Low"
    },
    "pomegranate": {
        "sowing_window": "July – August / January – February",
        "season": "Perennial / Horticultural",
        "seed_cost_per_acre": 15000,
        "fertilizer_cost_per_acre": 12000,
        "labor_cost_per_acre": 14000,
        "machinery_cost_per_acre": 5000,
        "irrigation_cost_per_acre": 5000,
        "pesticide_cost_per_acre": 6000,
        "water_requirement_mm": 700,
        "expected_yield_quintal_per_acre": 45,
        "market_price_per_quintal": 8000,
        "market_demand": "High",
        "market_risk": "High",
        "water_sensitivity": "Medium"
    },
    "banana": {
        "sowing_window": "June – July / October – November",
        "season": "Perennial (12-14 months)",
        "seed_cost_per_acre": 18000,
        "fertilizer_cost_per_acre": 15000,
        "labor_cost_per_acre": 16000,
        "machinery_cost_per_acre": 6000,
        "irrigation_cost_per_acre": 8000,
        "pesticide_cost_per_acre": 5000,
        "water_requirement_mm": 1600,
        "expected_yield_quintal_per_acre": 250,
        "market_price_per_quintal": 1800,
        "market_demand": "High",
        "market_risk": "Medium",
        "water_sensitivity": "High"
    },
    "mango": {
        "sowing_window": "July – September",
        "season": "Perennial",
        "seed_cost_per_acre": 12000,
        "fertilizer_cost_per_acre": 8000,
        "labor_cost_per_acre": 10000,
        "machinery_cost_per_acre": 4000,
        "irrigation_cost_per_acre": 4000,
        "pesticide_cost_per_acre": 5000,
        "water_requirement_mm": 800,
        "expected_yield_quintal_per_acre": 40,
        "market_price_per_quintal": 4500,
        "market_demand": "High",
        "market_risk": "Medium",
        "water_sensitivity": "Medium"
    },
    "grapes": {
        "sowing_window": "October – November",
        "season": "Perennial",
        "seed_cost_per_acre": 25000,
        "fertilizer_cost_per_acre": 18000,
        "labor_cost_per_acre": 22000,
        "machinery_cost_per_acre": 7000,
        "irrigation_cost_per_acre": 7000,
        "pesticide_cost_per_acre": 10000,
        "water_requirement_mm": 700,
        "expected_yield_quintal_per_acre": 90,
        "market_price_per_quintal": 5000,
        "market_demand": "High",
        "market_risk": "High",
        "water_sensitivity": "Medium"
    },
    "watermelon": {
        "sowing_window": "January 15 – February 28 (Zaid)",
        "season": "Zaid (Summer)",
        "seed_cost_per_acre": 3500,
        "fertilizer_cost_per_acre": 4500,
        "labor_cost_per_acre": 5000,
        "machinery_cost_per_acre": 2500,
        "irrigation_cost_per_acre": 3000,
        "pesticide_cost_per_acre": 2000,
        "water_requirement_mm": 500,
        "expected_yield_quintal_per_acre": 150,
        "market_price_per_quintal": 1200,
        "market_demand": "Medium",
        "market_risk": "High",
        "water_sensitivity": "Medium"
    },
    "muskmelon": {
        "sowing_window": "January 15 – February 28 (Zaid)",
        "season": "Zaid (Summer)",
        "seed_cost_per_acre": 3200,
        "fertilizer_cost_per_acre": 4000,
        "labor_cost_per_acre": 4800,
        "machinery_cost_per_acre": 2200,
        "irrigation_cost_per_acre": 2800,
        "pesticide_cost_per_acre": 1800,
        "water_requirement_mm": 450,
        "expected_yield_quintal_per_acre": 120,
        "market_price_per_quintal": 1400,
        "market_demand": "Medium",
        "market_risk": "High",
        "water_sensitivity": "Medium"
    },
    "apple": {
        "sowing_window": "December – March",
        "season": "Temperate Perennial",
        "seed_cost_per_acre": 20000,
        "fertilizer_cost_per_acre": 14000,
        "labor_cost_per_acre": 18000,
        "machinery_cost_per_acre": 6000,
        "irrigation_cost_per_acre": 5000,
        "pesticide_cost_per_acre": 8000,
        "water_requirement_mm": 900,
        "expected_yield_quintal_per_acre": 60,
        "market_price_per_quintal": 7000,
        "market_demand": "High",
        "market_risk": "Medium",
        "water_sensitivity": "Medium"
    },
    "orange": {
        "sowing_window": "June – August",
        "season": "Perennial",
        "seed_cost_per_acre": 12000,
        "fertilizer_cost_per_acre": 9000,
        "labor_cost_per_acre": 11000,
        "machinery_cost_per_acre": 4000,
        "irrigation_cost_per_acre": 4500,
        "pesticide_cost_per_acre": 5000,
        "water_requirement_mm": 850,
        "expected_yield_quintal_per_acre": 50,
        "market_price_per_quintal": 3800,
        "market_demand": "High",
        "market_risk": "Medium",
        "water_sensitivity": "Medium"
    },
    "papaya": {
        "sowing_window": "June – July / September – October",
        "season": "Perennial (1-2 years)",
        "seed_cost_per_acre": 6000,
        "fertilizer_cost_per_acre": 8000,
        "labor_cost_per_acre": 9000,
        "machinery_cost_per_acre": 3000,
        "irrigation_cost_per_acre": 4000,
        "pesticide_cost_per_acre": 3500,
        "water_requirement_mm": 1000,
        "expected_yield_quintal_per_acre": 180,
        "market_price_per_quintal": 1600,
        "market_demand": "High",
        "market_risk": "Medium",
        "water_sensitivity": "High"
    },
    "coconut": {
        "sowing_window": "May – June",
        "season": "Long-term Perennial",
        "seed_cost_per_acre": 10000,
        "fertilizer_cost_per_acre": 7000,
        "labor_cost_per_acre": 8000,
        "machinery_cost_per_acre": 3000,
        "irrigation_cost_per_acre": 4000,
        "pesticide_cost_per_acre": 2500,
        "water_requirement_mm": 1300,
        "expected_yield_quintal_per_acre": 40,
        "market_price_per_quintal": 3200,
        "market_demand": "High",
        "market_risk": "Low",
        "water_sensitivity": "High"
    },
    "cotton": {
        "sowing_window": "June 1 – June 30 (Kharif)",
        "season": "Kharif",
        "seed_cost_per_acre": 2800,
        "fertilizer_cost_per_acre": 4500,
        "labor_cost_per_acre": 6500,
        "machinery_cost_per_acre": 3000,
        "irrigation_cost_per_acre": 2200,
        "pesticide_cost_per_acre": 3000,
        "water_requirement_mm": 750,
        "expected_yield_quintal_per_acre": 10,
        "market_price_per_quintal": 6600,
        "market_demand": "High",
        "market_risk": "High",
        "water_sensitivity": "Medium"
    },
    "jute": {
        "sowing_window": "March 15 – May 15 (Pre-Kharif)",
        "season": "Pre-Kharif",
        "seed_cost_per_acre": 1800,
        "fertilizer_cost_per_acre": 3000,
        "labor_cost_per_acre": 5500,
        "machinery_cost_per_acre": 2200,
        "irrigation_cost_per_acre": 1500,
        "pesticide_cost_per_acre": 1200,
        "water_requirement_mm": 600,
        "expected_yield_quintal_per_acre": 12,
        "market_price_per_quintal": 5000,
        "market_demand": "Medium",
        "market_risk": "Low",
        "water_sensitivity": "Medium"
    },
    "coffee": {
        "sowing_window": "June – August",
        "season": "Perennial Plantation",
        "seed_cost_per_acre": 12000,
        "fertilizer_cost_per_acre": 10000,
        "labor_cost_per_acre": 14000,
        "machinery_cost_per_acre": 4000,
        "irrigation_cost_per_acre": 3500,
        "pesticide_cost_per_acre": 4500,
        "water_requirement_mm": 1100,
        "expected_yield_quintal_per_acre": 10,
        "market_price_per_quintal": 18000,
        "market_demand": "High",
        "market_risk": "Medium",
        "water_sensitivity": "Medium"
    }
}

DEFAULT_METRICS = {
    "sowing_window": "Regional recommendation unavailable",
    "season": "General",
    "seed_cost_per_acre": 2500,
    "fertilizer_cost_per_acre": 3500,
    "labor_cost_per_acre": 5000,
    "machinery_cost_per_acre": 2500,
    "irrigation_cost_per_acre": 2000,
    "pesticide_cost_per_acre": 2000,
    "water_requirement_mm": 600,
    "expected_yield_quintal_per_acre": 10,
    "market_price_per_quintal": 3000,
    "market_demand": "Moderate",
    "market_risk": "Medium",
    "water_sensitivity": "Medium"
}